// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow that generates a grounded response based on a search query using the Gemini API and Google Search grounding tool.
 *
 * - generateGroundedResponse - A function that accepts a search query and returns a grounded response with citations.
 */

import {ai} from '@/ai/genkit';
import { GenerateGroundedResponseInputSchema, GenerateGroundedResponseOutputSchema, type GenerateGroundedResponseInput, type GenerateGroundedResponseOutput } from '@/ai/schemas/grounded-response-schema';

export async function generateGroundedResponse(input: GenerateGroundedResponseInput): Promise<GenerateGroundedResponseOutput> {
  return generateGroundedResponseFlow(input);
}

const generateGroundedResponseFlow = ai.defineFlow(
  {
    name: 'generateGroundedResponseFlow',
    inputSchema: GenerateGroundedResponseInputSchema,
    outputSchema: GenerateGroundedResponseOutputSchema,
  },
  async (input) => {
    const grounding_tool = {
        google_search: {}
    };

    const config = {
        tools: [grounding_tool]
    };

    const response = await ai.generate({
        model: 'googleai/gemini-2.5-flash',
        prompt: input.query,
        config
    });

    const output = response.output();
    const groundingMetadata = response.groundingMetadata;

    return {
      response: output!.response,
      webSearchQueries: groundingMetadata?.webSearchQueries,
      searchEntryPoint: groundingMetadata?.searchEntryPoint,
      groundingChunks: groundingMetadata?.groundingChunks,
      groundingSupports: groundingMetadata?.groundingSupports
    };
  }
);
