// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow that generates a grounded response based on a search query using the Gemini API and Google Search grounding tool.
 *
 * - generateGroundedResponse - A function that accepts a search query and returns a grounded response with citations.
 * - GenerateGroundedResponseInput - The input type for the generateGroundedResponse function.
 * - GenerateGroundedResponseOutput - The return type for the generateGroundedResponse function, including the grounded response and metadata.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateGroundedResponseInputSchema = z.object({
  query: z.string().describe('The search query to be used for generating a grounded response.'),
});
export type GenerateGroundedResponseInput = z.infer<typeof GenerateGroundedResponseInputSchema>;

const GenerateGroundedResponseOutputSchema = z.object({
  response: z.string().describe('The grounded response generated by the Gemini API.'),
  webSearchQueries: z.array(z.string()).optional().describe('Array of the search queries used.'),
  searchEntryPoint: z.string().optional().describe('Contains the HTML and CSS to render the required Search Suggestions.'),
  groundingChunks: z.array(z.object({
    web: z.object({
      uri: z.string(),
      title: z.string()
    })
  })).optional().describe('Array of objects containing the web sources (uri and title).'),
  groundingSupports: z.array(z.object({
    segment: z.object({
      startIndex: z.number(),
      endIndex: z.number(),
      text: z.string()
    }),
    groundingChunkIndices: z.array(z.number())
  })).optional().describe('Array of chunks to connect model response text to the sources.')
});
export type GenerateGroundedResponseOutput = z.infer<typeof GenerateGroundedResponseOutputSchema>;

export async function generateGroundedResponse(input: GenerateGroundedResponseInput): Promise<GenerateGroundedResponseOutput> {
  return generateGroundedResponseFlow(input);
}

const generateGroundedResponsePrompt = ai.definePrompt({
  name: 'generateGroundedResponsePrompt',
  input: {schema: GenerateGroundedResponseInputSchema},
  output: {schema: z.object({response: z.string()})},
  prompt: `{{query}}`,
  tools: []
});

const generateGroundedResponseFlow = ai.defineFlow(
  {
    name: 'generateGroundedResponseFlow',
    inputSchema: GenerateGroundedResponseInputSchema,
    outputSchema: GenerateGroundedResponseOutputSchema,
  },
  async input => {
    const grounding_tool = {
        google_search: {}
    };

    const config = {
        tools: [grounding_tool]
    };

    const response = await ai.generate({
        model: 'googleai/gemini-2.5-flash',
        prompt: input.query,
        config
    });

    return {
      response: response.text,
      webSearchQueries: response.groundingMetadata?.webSearchQueries,
      searchEntryPoint: response.groundingMetadata?.searchEntryPoint,
      groundingChunks: response.groundingMetadata?.groundingChunks,
      groundingSupports: response.groundingMetadata?.groundingSupports
    };
  }
);
