/**
 * @fileOverview Schemas for the grounded response flow.
 *
 * - GenerateGroundedResponseInputSchema - The input schema for the generateGroundedResponse function.
 * - GenerateGroundedResponseOutputSchema - The output schema for the generateGroundedResponse function.
 * - GenerateGroundedResponseInput - The input type for the generateGroundedResponse function.
 * - GenerateGroundedResponseOutput - The return type for the generateGroundedResponse function.
 */

import {z} from 'genkit';

export const GenerateGroundedResponseInputSchema = z.object({
  query: z.string().describe('The search query to be used for generating a grounded response.'),
});
export type GenerateGroundedResponseInput = z.infer<typeof GenerateGroundedResponseInputSchema>;

export const GenerateGroundedResponseOutputSchema = z.object({
  response: z.string().describe('The grounded response generated by the Gemini API.'),
  webSearchQueries: z.array(z.string()).optional().describe('Array of the search queries used.'),
  searchEntryPoint: z.string().optional().describe('Contains the HTML and CSS to render the required Search Suggestions.'),
  groundingChunks: z.array(z.union([
    z.object({
      web: z.object({
        uri: z.string(),
        title: z.string()
      })
    }),
    z.object({
      maps: z.object({
        uri: z.string(),
        title: z.string(),
        text: z.string()
      })
    })
  ])).optional().describe('Array of objects containing the web or map sources.'),
  groundingSupports: z.array(z.object({
    segment: z.object({
      startIndex: z.number(),
      endIndex: z.number(),
      text: z.string()
    }),
    groundingChunkIndices: z.array(z.number())
  })).optional().describe('Array of chunks to connect model response text to the sources.')
});
export type GenerateGroundedResponseOutput = z.infer<typeof GenerateGroundedResponseOutputSchema>;
