/**
 * @fileOverview Schemas for the hotel finding flow.
 */

import { z } from 'genkit';

// Input schema for the hotel finding flow
export const FindHotelsInputSchema = z.object({
  destination: z.string().describe('The destination city to search for hotels in (e.g., "Tokyo").'),
});
export type FindHotelsInput = z.infer<typeof FindHotelsInputSchema>;

// Schema for a single hotel's details
export const HotelSchema = z.object({
  name: z.string().describe('The name of the hotel.'),
  address: z.string().describe('The full address of the hotel.'),
  imageUrl: z.string().nullable().describe('A URL for a photo of the hotel.'),
  description: z.string().describe('A brief, helpful description of the hotel generated by an AI.'),
});
export type Hotel = z.infer<typeof HotelSchema>;

// Output schema containing a list of hotels
export const FindHotelsOutputSchema = z.object({
  hotels: z.array(HotelSchema).describe('A list of up to 6 recommended hotels.'),
});
export type FindHotelsOutput = z.infer<typeof FindHotelsOutputSchema>;

    