import type { GenerateItineraryOutput } from "@/ai/schemas/itinerary-schema";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { MapPin, Building, Utensils, Mountain } from "lucide-react";
import Image from "next/image";

interface ItineraryDisplayProps {
  data: GenerateItineraryOutput;
}

const LocationIcon = ({ name }: { name: string }) => {
  const lowerCaseName = name.toLowerCase();
  if (lowerCaseName.includes('restaurant') || lowerCaseName.includes('cafe') || lowerCaseName.includes('market')) {
    return <Utensils className="h-5 w-5 text-accent" />;
  }
  if (lowerCaseName.includes('museum') || lowerCaseName.includes('temple') || lowerCaseName.includes('shrine') || lowerCaseName.includes('castle') || lowerCaseName.includes('tower')) {
    return <Building className="h-5 w-5 text-accent" />;
  }
  if (lowerCaseName.includes('park') || lowerCaseName.includes('garden') || lowerCaseName.includes('mountain')) {
      return <Mountain className="h-5 w-5 text-accent" />
  }
  return <MapPin className="h-5 w-5 text-accent" />;
};


export function ItineraryDisplay({ data }: ItineraryDisplayProps) {
  const { itinerary } = data;

  return (
    <div className="animate-in fade-in duration-500 space-y-6">
       <Card className="shadow-lg border-primary/20">
          <CardHeader>
            <CardTitle className="font-headline text-3xl text-primary">
              Your 3-Day Travel Itinerary
            </CardTitle>
            <CardDescription>
              This plan was generated by AI based on the YouTube video you selected.
            </CardDescription>
          </CardHeader>
        </Card>

      <Accordion type="single" collapsible defaultValue="item-0" className="w-full">
        {itinerary.map((day, dayIndex) => (
          <AccordionItem value={`item-${dayIndex}`} key={day.day}>
            <AccordionTrigger className="text-xl font-headline text-primary hover:no-underline">
              <div className="flex items-center gap-4">
                <div className="flex-shrink-0 h-10 w-10 bg-primary text-primary-foreground rounded-full flex items-center justify-center text-lg font-bold">
                    {day.day}
                </div>
                <span>{day.title}</span>
              </div>
            </AccordionTrigger>
            <AccordionContent>
              <div className="space-y-4 pt-4">
                {day.locations.map((location, locIndex) => (
                  <Card key={locIndex} className="overflow-hidden">
                    <div className="grid grid-cols-1 md:grid-cols-3">
                      <div className="md:col-span-1">
                          {location.imageUrl ? (
                            <div className="relative h-48 w-full">
                              <Image
                                src={location.imageUrl}
                                alt={location.name}
                                fill
                                className="object-cover"
                                data-ai-hint="location photo"
                              />
                             </div>
                          ) : (
                            <div className="h-48 w-full bg-muted flex items-center justify-center">
                                <MapPin className="h-12 w-12 text-muted-foreground" />
                            </div>
                          )}
                      </div>
                      <div className="md:col-span-2">
                        <CardHeader>
                            <CardTitle className="flex items-center gap-3">
                                <LocationIcon name={location.name} />
                                <span>{location.name}</span>
                            </CardTitle>
                        </CardHeader>
                        <CardContent>
                          <p className="text-muted-foreground mb-2">
                            {location.description}
                          </p>
                          <p className="text-xs text-muted-foreground/80">{location.address}</p>
                        </CardContent>
                      </div>
                    </div>
                  </Card>
                ))}
              </div>
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  );
}
